# ==============================
# agentscope-robert 模块配置
# ==============================

server.port=${SERVER_PORT:18098}

# Spring Application Name
spring.application.name=agentscope-robert-a2a-client

## Disable Spring Boot banner
##spring.main.banner-mode=on
#
# ==============================
# A2A Server Configuration
# ==============================
# Disable A2A Server (this is A2A Client only)
agentscope.a2a.server.enabled=false
#agentscope.a2a.server.card.name=doctor-assistant
#agentscope.a2a.server.card.description=\u667a\u80fd\u52a9\u624b\uff0c\u652f\u6301\u591a\u8f6e\u5bf9\u8bdd\u548c\u5de5\u5177\u8c03\u7528
#agentscope.a2a.server.card.version=1.0.0
#
## ==============================
## Nacos A2A Registry & Discovery
## ==============================

# AgentscopeA2aNacosAutoConfiguration 才会生效，会自动注入NacosAgentCardResolver bean
# 这个参数在idea启动参数配置，避免泄漏api-key
agentscope.dashscope.api-key=${DASHSCOPE_API_KEY}
#agentscope.agent.name=robert-a2a-agent

agentscope.a2a.nacos.enabled=true
agentscope.a2a.nacos.server-addr=${NACOS_SERVER_ADDRESS:localhost:8848}
agentscope.a2a.nacos.username=${NACOS_USERNAME:nacos}
agentscope.a2a.nacos.password=${NACOS_PASSWORD:nacos}
agentscope.a2a.nacos.namespace=public
agentscope.a2a.nacos.discovery.enabled=true

# Disable Nacos Prompt Agent (not needed for A2A client)
agentscope.nacos.prompt.enabled=false
