# ==============================
# agentscope-robert 模块配置
# ==============================

server.port=${SERVER_PORT:18096}

# Spring Application Name
spring.application.name=agentscope-robert

# Disable Spring Boot banner
spring.main.banner-mode=off
